### ISSUE TITLE
게시판 API 만들기

### ISSUE THREAD

**Issue by hoduulmu** [HoduUlmu/project-board#5]
api를 만든다
* [x] API 설계
* [x] API 테스트 정의
* [x] API 구현
  * [x] 게시글 API
  * [x] 댓글 API

**Comment by HoduUlmu** [comment]
api 설계 완료

- https://docs.google.com/spreadsheets/d/1V8Ndj2gmbFi0Ttnl9BtZJqPRz0dgNmsH3sr3iv3kzkA/edit?usp=sharing

**Comment by HoduUlmu** [comment]
api 테스트 완료
- Spring Data Rest 활용한 Integration 테스트

댓글, 게시글 api 구현 완료
- Spring Data Rest 활용하여 restful api 자동 구현

**Comment by HoduUlmu** [comment]
#1 commit으로 실수로 몇개 들어감
